### ISSUE TITLE
SyntaxError: f-string expression part cannot include a backslash

### ISSUE THREAD

**Issue by NotTheD** [Alex-FIR-IT/Loader_for_webinar.ru#1]
Добрый день!
При выполнении main.py возникает ошибка SyntaxError: f-string expression part cannot include a backslash.

Полный текст:

(venv) D:\MIP>python main.py
Traceback (most recent call last):
  File "D:\MIP\main.py", line 8, in <module>
    from scripts.download import download_webinar
  File "D:\MIP\scripts\download.py", line 145
    )
    ^
SyntaxError: f-string expression part cannot include a backslash

Ни один из способов, найденных в интернете не помог. Если убрать "\n" из строки, то скрипт идет дальше, спрашивает ссылку, потом про слияние чанков потом опять возвращает ошибку, но другую:

f'{join(video_chunks_urls_with_numeration_for_output)}')
       ^^^^
NameError: name 'join' is not defined

На всякий случай: Python 3.11

**Comment by Alex-FIR-IT** [comment]
Ошибка была связана с тем, что python 3.11 не поддерживал определенный синтаксис. Поправил форматирование, ошибка должна была уйти.
